### PR TITLE
Add upvotes and downvotes

### PR DESCRIPTION
**Pull request by peyman3d**
Hi again, 
As you asked I created PR for upvotes and downvotes. hope that would help :)

### CODE REVIEW

**Comment by peyman3d** [comment]
@overtrue Hi, Can you check this please? 😊

**Comment by overtrue** [comment]
https://styleci.io/analyses/qy06oN

**Comment by overtrue** [comment]
use space replace tab.

**Comment by overtrue** [comment]
@peyman3d Can you update the README?

**Comment by peyman3d** [comment]
Yes, sure :)

**Pull request merged**
